### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by dzeyelid** [githubschooljp/class-repo-sep-5-6#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by dzeyelid-ghost** [comment]
hello

**Comment by TakafumiYamaguchi814455** [comment]
hello

**Comment by Hiroki01Ichikawa** [comment]
hi

**Comment by wataruS1100** [comment]
hello

**Comment by sunaoshi-kyohei** [comment]
test

**Comment by KosukeShimazu** [comment]
Hello!!

**Comment by t2ch18** [comment]
hello

**Comment by HitoshiYamamoto-Honda** [comment]
Hello Git san

**Comment by Okubo-Ryosuke** [comment]
Hello

**Comment by GenKuroda** [comment]
**Hello,**

**Comment by hashiguchi01** [comment]
hello

**Comment by HiromichiWakatsuki** [comment]
konnnitiha.

**Comment by TaisukeOshima** [comment]
OK

**Comment by unreal906** [comment]
hello

**Comment by Kakazu-Masashi** [comment]
hello
